baseurl = "https://forlos.github.io"
languageCode = "en"
defaultcontentlanguage = "en"
theme = "hugo-coder"
title = "Breaking things for fun and no profit"
enableRobotsTXT = true

paginate = 20
canonifyurls = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+
    [markup.highlight]
    style = "dracula"
    lineNos = true
    lineNumbersInTable = true
    guessSyntax = false

[taxonomies]
    tag = "tags"


[params]
    author = "Forlos"
    info = "Breaking random stuff until it works"
    keywords = "rust, reverse engineering, visual novel, programming, hacking"

    hidecopyright = true
    hidecredits = true
    colorscheme = "dark"


[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/forlos/"

[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "Posts"
    weight = 2
    url  = "/posts"
[[menu.main]]
    name = "Tags"
    weight = 3
    url  = "/tags"
[[menu.main]]
    name = "CV"
    weight = 10
    url = "/cv"
